### PR TITLE
Amending Italian Translations

### PR DESCRIPTION
**Pull request by mega5800**
:+1::tada: First off, thanks for taking the time to contribute! :tada::+1:

Please fill out the following checklist:

- [x] Added tests for any bug fixes that changed existing code
- [x] Added tests for any new behavior
- [x] All unit tests are passing (please make sure all tests are passing for your branch/PR at https://ci.appveyor.com/project/activescott/lessmsi/history )

If you need any help at all, feel free to submit the PR and @-mention activescott and I'll be happy to assist!

Hello @activescott.

I took care of this [ticket](https://github.com/activescott/lessmsi/issues/206).

Here is the amended file filter translation:
image

@bovirus, I took the liberty and amended the Italian translations where upper case words should be lowercase.
For example:
image

I also amended the tests to use the new and correct translations

Thank you.

### CODE REVIEW

**Comment by mega5800** [comment]
Hello @activescott.

Can you please check this pull request and let me know if something else is required.
I'd like to start working on other tickets as well.

Thank you.

**Review by activescott — APPROVED** [review]

**Comment by activescott** [comment]
Thanks @mega5800. Sorry, I just missed this one in my list of GitHub notifications. Thanks for your work. It will be best for you to tag me on an issue you plan to work on before you start working to confirm that we're aligned. I want to make sure that you get the most impact for the work you're do!

**Comment by mega5800** [comment]
Hello @activescott.

Thank you for approving this pull request.
I think I will continue working on this [ticket](https://github.com/activescott/lessmsi/issues/167).
I already have an existing code for supporting this feature and now I'd like to add the required tests.

Hopefully, I will send a new pull request during this weekend.

Thank you.

**Comment by activescott** [comment]
@mega5800 sounds good!

**Pull request merged**
